/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AddressPrecompile__factory } from "./AddressPrecompile__factory";
export { BankPrecompile__factory } from "./BankPrecompile__factory";
export { StakingPrecompile__factory } from "./StakingPrecompile__factory";
export { WasmPrecompile__factory } from "./WasmPrecompile__factory";
