/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AddressPrecompile } from "./AddressPrecompile";
export type { BankPrecompile } from "./BankPrecompile";
export type { StakingPrecompile } from "./StakingPrecompile";
export type { WasmPrecompile } from "./WasmPrecompile";
