/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  claim_able_time: number;
  fund: Addr;
  gov?: Addr | null;
  merkle_root: string;
  total_reward: number;
  ve_token: Addr;
}
export type ExecuteMsg = {
  update_config: {
    update_config_msg: UpdateConfigMsg;
  };
} | {
  claim: {
    amount: string;
    proof: string;
  };
} | {
  accept_gov: {};
};
export interface UpdateConfigMsg {
  fund?: Addr | null;
  new_gov?: Addr | null;
}
export type QueryMsg = {
  config: {};
} | {
  config_state: {};
} | {
  claimed: {
    address: Addr;
  };
};
export type Boolean = boolean;
export interface ConfigResponse {
  claim_able_time: number;
  fund: Addr;
  gov: Addr;
  merkle_root: string;
  new_gov?: Addr | null;
  total_reward: number;
  ve_token: Addr;
}
export interface ConfigStateResponse {
  total_claimed: number;
  total_claimed_count: number;
}
export type MerkleVeDropExecuteMsg = ExecuteMsg;
