/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal256 = string;
export interface BorrowRateResponse {
  rate: Decimal256;
  [k: string]: unknown;
}
export interface ConfigResponse {
  base_rate: Decimal256;
  interest_multiplier: Decimal256;
  owner: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  update_config: {
    base_rate?: Decimal256 | null;
    interest_multiplier?: Decimal256 | null;
    [k: string]: unknown;
  };
} | {
  set_owner: {
    new_owner_addr: string;
    [k: string]: unknown;
  };
} | {
  accept_ownership: {
    [k: string]: unknown;
  };
};
export interface InstantiateMsg {
  base_rate: Decimal256;
  interest_multiplier: Decimal256;
  owner: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  config: {
    [k: string]: unknown;
  };
} | {
  borrow_rate: {
    market_balance: Uint256;
    total_liabilities: Decimal256;
    total_reserves: Decimal256;
    [k: string]: unknown;
  };
};
export type Uint256 = string;
export type InterestModelExecuteMsg = ExecuteMsg;