/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface ConfigResponse {
  base_asset: string;
  owner: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  update_config: {
    owner?: string | null;
    [k: string]: unknown;
  };
} | {
  register_feeder: {
    asset: string;
    feeder: string;
    [k: string]: unknown;
  };
} | {
  feed_price: {
    prices: [string, Decimal256][];
    [k: string]: unknown;
  };
};
export type Decimal256 = string;
export interface FeederResponse {
  asset: string;
  feeder: string;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  base_asset: string;
  owner: string;
  [k: string]: unknown;
}
export interface PriceResponse {
  last_updated_base: number;
  last_updated_quote: number;
  rate: Decimal256;
  [k: string]: unknown;
}
export interface PricesResponse {
  prices: PricesResponseElem[];
  [k: string]: unknown;
}
export interface PricesResponseElem {
  asset: string;
  last_updated_time: number;
  price: Decimal256;
  [k: string]: unknown;
}
export type QueryMsg = {
  config: {
    [k: string]: unknown;
  };
} | {
  feeder: {
    asset: string;
    [k: string]: unknown;
  };
} | {
  price: {
    base: string;
    quote: string;
    [k: string]: unknown;
  };
} | {
  prices: {
    limit?: number | null;
    start_after?: string | null;
    [k: string]: unknown;
  };
};
export type OracleExecuteMsg = ExecuteMsg;