/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  extension?: Metadata | null;
  minter?: Addr | null;
  name: string;
  owner?: Addr | null;
  symbol: string;
  token_code_id: number;
  token_uri: string;
}
export interface Metadata {
  animation_url?: string | null;
  attributes?: Trait[] | null;
  background_color?: string | null;
  description?: string | null;
  external_url?: string | null;
  image?: string | null;
  image_data?: string | null;
  name?: string | null;
  youtube_url?: string | null;
}
export interface Trait {
  display_type?: string | null;
  trait_type: string;
  value: string;
}
export type ExecuteMsg = {
  update_minter: {
    minter: Addr;
  };
} | {
  mint: {
    users: Addr[];
  };
} | {
  update_ownership: Action;
};
export type Action = {
  transfer_ownership: {
    expiry?: Expiration | null;
    new_owner: string;
  };
} | "accept_ownership" | "renounce_ownership";
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type QueryMsg = {
  query_config: {};
} | {
  get_ownership: {};
};
export interface OwnershipForAddr {
  owner?: Addr | null;
  pending_expiry?: Expiration | null;
  pending_owner?: Addr | null;
}
export interface Config {
  cw721_address: Addr;
  extension?: Metadata | null;
  minter: Addr;
  token_uri: string;
  unused_token_id: number;
}
export type MedalExecuteMsg = ExecuteMsg;