/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint128 = string;
export interface InstantiateMsg {
  first_mint_end_time: number;
  first_mint_start_time: number;
  max_mint_count: number;
  mint_payment_address: Addr;
  name: string;
  owner?: Addr | null;
  pay_denom: string;
  royalty_payment_address: Addr;
  royalty_percentage: number;
  symbol: string;
  token_code_id: number;
  token_uri: string;
  uint_price: Uint128;
}
export type ExecuteMsg = {
  set_white_list: {
    write_list: WhiteListUserMsg[];
  };
} | {
  mint: {};
} | {
  update_ownership: Action;
};
export type Action = {
  transfer_ownership: {
    expiry?: Expiration | null;
    new_owner: string;
  };
} | "accept_ownership" | "renounce_ownership";
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface WhiteListUserMsg {
  limit_count: number;
  user: Addr;
}
export type QueryMsg = {
  query_white_list_user_info: {
    user: Addr;
  };
} | {
  query_config: {};
} | {
  get_ownership: {};
};
export interface OwnershipForAddr {
  owner?: Addr | null;
  pending_expiry?: Expiration | null;
  pending_owner?: Addr | null;
}
export interface Config {
  cw721_address: Addr;
  first_mint_end_time: number;
  first_mint_start_time: number;
  max_mint_count: number;
  mint_payment_address: Addr;
  pay_denom: string;
  royalty_payment_address: Addr;
  royalty_percentage: number;
  token_uri: string;
  uint_price: Uint128;
  unused_token_id: number;
}
export interface WhiteListUser {
  count: number;
  limit_count: number;
}
export type SeiYanSeiNftExecuteMsg = ExecuteMsg;