/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _4 from "./MockOracle.types";
import * as _5 from "./MockOracle.client";
import * as _6 from "./OraclePyth.types";
import * as _7 from "./OraclePyth.client";
export namespace oracleContracts {
  export const MockOracle = { ..._4,
    ..._5
  };
  export const OraclePyth = { ..._6,
    ..._7
  };
}