/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./MockOracle.types";
import * as _1 from "./MockOracle.client";
import * as _2 from "./OraclePyth.types";
import * as _3 from "./OraclePyth.client";
export namespace oracleContracts {
  export const MockOracle = { ..._0,
    ..._1
  };
  export const OraclePyth = { ..._2,
    ..._3
  };
}