/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Cw2981Royalties.types";
import * as _1 from "./Cw2981Royalties.client";
export namespace nftContracts {
  export const Cw2981Royalties = { ..._0,
    ..._1
  };
}