/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Hub.types";
import * as _1 from "./Hub.client";
import * as _2 from "./Reward.types";
import * as _3 from "./Reward.client";
import * as _4 from "./RewardsDispatcher.types";
import * as _5 from "./RewardsDispatcher.client";
import * as _6 from "./TokenBsei.types";
import * as _7 from "./TokenBsei.client";
import * as _8 from "./TokenStsei.types";
import * as _9 from "./TokenStsei.client";
import * as _10 from "./ValidatorsRegistry.types";
import * as _11 from "./ValidatorsRegistry.client";
export namespace stakingContracts {
  export const Hub = { ..._0,
    ..._1
  };
  export const Reward = { ..._2,
    ..._3
  };
  export const RewardsDispatcher = { ..._4,
    ..._5
  };
  export const TokenBsei = { ..._6,
    ..._7
  };
  export const TokenStsei = { ..._8,
    ..._9
  };
  export const ValidatorsRegistry = { ..._10,
    ..._11
  };
}