/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _8 from "./Hub.types";
import * as _9 from "./Hub.client";
import * as _10 from "./Reward.types";
import * as _11 from "./Reward.client";
import * as _12 from "./RewardsDispatcher.types";
import * as _13 from "./RewardsDispatcher.client";
import * as _14 from "./TokenBsei.types";
import * as _15 from "./TokenBsei.client";
import * as _16 from "./TokenStsei.types";
import * as _17 from "./TokenStsei.client";
import * as _18 from "./ValidatorsRegistry.types";
import * as _19 from "./ValidatorsRegistry.client";
export namespace stakingContracts {
  export const Hub = { ..._8,
    ..._9
  };
  export const Reward = { ..._10,
    ..._11
  };
  export const RewardsDispatcher = { ..._12,
    ..._13
  };
  export const TokenBsei = { ..._14,
    ..._15
  };
  export const TokenStsei = { ..._16,
    ..._17
  };
  export const ValidatorsRegistry = { ..._18,
    ..._19
  };
}