/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _36 from "./BlindBox.types";
import * as _37 from "./BlindBox.client";
import * as _38 from "./BlindBoxReward.types";
import * as _39 from "./BlindBoxReward.client";
import * as _40 from "./Kpt.types";
import * as _41 from "./Kpt.client";
import * as _42 from "./KptFund.types";
import * as _43 from "./KptFund.client";
import * as _44 from "./StakingRewards.types";
import * as _45 from "./StakingRewards.client";
import * as _46 from "./VeKpt.types";
import * as _47 from "./VeKpt.client";
import * as _48 from "./VeKptBoost.types";
import * as _49 from "./VeKptBoost.client";
import * as _50 from "./VeKptMiner.types";
import * as _51 from "./VeKptMiner.client";
export namespace kptContracts {
  export const BlindBox = { ..._36,
    ..._37
  };
  export const BlindBoxReward = { ..._38,
    ..._39
  };
  export const Kpt = { ..._40,
    ..._41
  };
  export const KptFund = { ..._42,
    ..._43
  };
  export const StakingRewards = { ..._44,
    ..._45
  };
  export const VeKpt = { ..._46,
    ..._47
  };
  export const VeKptBoost = { ..._48,
    ..._49
  };
  export const VeKptMiner = { ..._50,
    ..._51
  };
}