/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint64 = string;
export type Addr = string;
export interface InstantiateMsg {
  claim_able_time: Uint64;
  exit_cycle: Uint64;
  gov?: Addr | null;
  kpt_addr: Addr;
  kusd_denom: string;
  kusd_reward_addr: Addr;
  ve_kpt_addr: Addr;
}
export type ExecuteMsg = {
  update_kpt_fund_config: {
    update_config_msg: UpdateConfigMsg;
  };
} | {
  refresh_reward: {
    account: Addr;
  };
} | {
  stake: {
    amount: Uint128;
  };
} | {
  unstake: {
    amount: Uint128;
  };
} | {
  withdraw: {
    user: Addr;
  };
} | {
  re_stake: {};
} | {
  get_reward: {};
} | {
  notify_reward_amount: {};
};
export type Uint128 = string;
export interface UpdateConfigMsg {
  claim_able_time?: Uint64 | null;
  gov?: Addr | null;
  kpt_addr?: Addr | null;
  kusd_denom?: string | null;
  kusd_reward_addr?: Addr | null;
  ve_kpt_addr?: Addr | null;
}
export type QueryMsg = {
  kpt_fund_config: {};
} | {
  get_claim_able_kpt: {
    user: Addr;
  };
} | {
  get_reserved_kpt_for_vesting: {
    user: Addr;
  };
} | {
  earned: {
    account: Addr;
  };
} | {
  get_claim_able_kusd: {
    account: Addr;
  };
} | {
  get_user_reward_per_token_paid: {
    account: Addr;
  };
} | {
  get_user_rewards: {
    account: Addr;
  };
} | {
  get_user_time2full_redemption: {
    account: Addr;
  };
} | {
  get_user_unstake_rate: {
    account: Addr;
  };
} | {
  get_user_last_withdraw_time: {
    account: Addr;
  };
};
export interface EarnedResponse {
  amount: Uint128;
}
export interface GetClaimAbleKptResponse {
  amount: Uint128;
}
export interface GetClaimAbleKusdResponse {
  amount: Uint128;
}
export interface GetReservedKptForVestingResponse {
  amount: Uint128;
}
export interface UserLastWithdrawTimeResponse {
  user_last_withdraw_time: Uint64;
}
export interface UserRewardPerTokenPaidResponse {
  user_reward_per_token_paid: Uint128;
}
export interface UserTime2FullRedemptionResponse {
  user_time2full_redemption: Uint64;
}
export type Uint256 = string;
export interface UserUnstakeRateResponse {
  user_unstake_rate: Uint256;
}
export interface KptFundConfigResponse {
  claim_able_time: Uint64;
  exit_cycle: Uint64;
  gov: Addr;
  kpt_addr: Addr;
  kusd_denom: string;
  kusd_reward_addr: Addr;
  kusd_reward_total_amount: Uint128;
  kusd_reward_total_paid_amount: Uint128;
  reward_per_token_stored: Uint128;
  ve_kpt_addr: Addr;
}
export type KptFundExecuteMsg = ExecuteMsg;