/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Hub.types";
import * as _1 from "./Hub.client";
import * as _2 from "./Reward.types";
import * as _3 from "./Reward.client";
import * as _4 from "./RewardsDispatcher.types";
import * as _5 from "./RewardsDispatcher.client";
import * as _6 from "./TokenBsei.types";
import * as _7 from "./TokenBsei.client";
import * as _8 from "./TokenStsei.types";
import * as _9 from "./TokenStsei.client";
import * as _10 from "./ValidatorsRegistry.types";
import * as _11 from "./ValidatorsRegistry.client";
import * as _12 from "./CustodyBase.types";
import * as _13 from "./CustodyBase.client";
import * as _14 from "./CustodyBsei.types";
import * as _15 from "./CustodyBsei.client";
import * as _16 from "./DistributionModel.types";
import * as _17 from "./DistributionModel.client";
import * as _18 from "./InterestModel.types";
import * as _19 from "./InterestModel.client";
import * as _20 from "./LiquidationQueue.types";
import * as _21 from "./LiquidationQueue.client";
import * as _22 from "./Market.types";
import * as _23 from "./Market.client";
import * as _24 from "./Oracle.types";
import * as _25 from "./Oracle.client";
import * as _26 from "./OraclePyth.types";
import * as _27 from "./OraclePyth.client";
import * as _28 from "./Overseer.types";
import * as _29 from "./Overseer.client";
import * as _30 from "./BassetConverter.types";
import * as _31 from "./BassetConverter.client";
import * as _32 from "./BassetToken.types";
import * as _33 from "./BassetToken.client";
import * as _34 from "./SwapExtention.types";
import * as _35 from "./SwapExtention.client";
export namespace contracts {
  export const Hub = { ..._0,
    ..._1
  };
  export const Reward = { ..._2,
    ..._3
  };
  export const RewardsDispatcher = { ..._4,
    ..._5
  };
  export const TokenBsei = { ..._6,
    ..._7
  };
  export const TokenStsei = { ..._8,
    ..._9
  };
  export const ValidatorsRegistry = { ..._10,
    ..._11
  };
  export const CustodyBase = { ..._12,
    ..._13
  };
  export const CustodyBsei = { ..._14,
    ..._15
  };
  export const DistributionModel = { ..._16,
    ..._17
  };
  export const InterestModel = { ..._18,
    ..._19
  };
  export const LiquidationQueue = { ..._20,
    ..._21
  };
  export const Market = { ..._22,
    ..._23
  };
  export const Oracle = { ..._24,
    ..._25
  };
  export const OraclePyth = { ..._26,
    ..._27
  };
  export const Overseer = { ..._28,
    ..._29
  };
  export const BassetConverter = { ..._30,
    ..._31
  };
  export const BassetToken = { ..._32,
    ..._33
  };
  export const SwapExtention = { ..._34,
    ..._35
  };
}