/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Uint128, AccruedRewardsResponse, ConfigResponse, ExecuteMsg, Decimal, HolderResponse, HoldersResponse, InstantiateMsg, QueryMsg, StateResponse } from "./Reward.types";
export interface RewardReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  state: () => Promise<StateResponse>;
  accruedRewards: ({
    address
  }: {
    address: string;
  }) => Promise<AccruedRewardsResponse>;
  holder: ({
    address
  }: {
    address: string;
  }) => Promise<HolderResponse>;
  holders: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<HoldersResponse>;
}
export class RewardQueryClient implements RewardReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.state = this.state.bind(this);
    this.accruedRewards = this.accruedRewards.bind(this);
    this.holder = this.holder.bind(this);
    this.holders = this.holders.bind(this);
  }

  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  state = async (): Promise<StateResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      state: {}
    });
  };
  accruedRewards = async ({
    address
  }: {
    address: string;
  }): Promise<AccruedRewardsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      accrued_rewards: {
        address
      }
    });
  };
  holder = async ({
    address
  }: {
    address: string;
  }): Promise<HolderResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      holder: {
        address
      }
    });
  };
  holders = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<HoldersResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      holders: {
        limit,
        start_after: startAfter
      }
    });
  };
}
export interface RewardInterface {
  contractAddress: string;
  sender: string;
  swapToRewardDenom: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateGlobalIndex: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  increaseBalance: ({
    address,
    amount
  }: {
    address: string;
    amount: Uint128;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  decreaseBalance: ({
    address,
    amount
  }: {
    address: string;
    amount: Uint128;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  claimRewards: ({
    recipient
  }: {
    recipient?: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateSwapContract: ({
    swapContract
  }: {
    swapContract: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateSwapDenom: ({
    isAdd,
    swapDenom
  }: {
    isAdd: boolean;
    swapDenom: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class RewardClient implements RewardInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.swapToRewardDenom = this.swapToRewardDenom.bind(this);
    this.updateGlobalIndex = this.updateGlobalIndex.bind(this);
    this.increaseBalance = this.increaseBalance.bind(this);
    this.decreaseBalance = this.decreaseBalance.bind(this);
    this.claimRewards = this.claimRewards.bind(this);
    this.updateSwapContract = this.updateSwapContract.bind(this);
    this.updateSwapDenom = this.updateSwapDenom.bind(this);
  }

  swapToRewardDenom = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      swap_to_reward_denom: {}
    }, fee, memo, _funds);
  };
  updateGlobalIndex = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_global_index: {}
    }, fee, memo, _funds);
  };
  increaseBalance = async ({
    address,
    amount
  }: {
    address: string;
    amount: Uint128;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      increase_balance: {
        address,
        amount
      }
    }, fee, memo, _funds);
  };
  decreaseBalance = async ({
    address,
    amount
  }: {
    address: string;
    amount: Uint128;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      decrease_balance: {
        address,
        amount
      }
    }, fee, memo, _funds);
  };
  claimRewards = async ({
    recipient
  }: {
    recipient?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim_rewards: {
        recipient
      }
    }, fee, memo, _funds);
  };
  updateSwapContract = async ({
    swapContract
  }: {
    swapContract: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_swap_contract: {
        swap_contract: swapContract
      }
    }, fee, memo, _funds);
  };
  updateSwapDenom = async ({
    isAdd,
    swapDenom
  }: {
    isAdd: boolean;
    swapDenom: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_swap_denom: {
        is_add: isAdd,
        swap_denom: swapDenom
      }
    }, fee, memo, _funds);
  };
}