/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  swap_to_reward_denom: {
    bsei_total_bonded: Uint128;
    stsei_total_bonded: Uint128;
    [k: string]: unknown;
  };
} | {
  update_config: {
    bsei_reward_contract?: string | null;
    bsei_reward_denom?: string | null;
    hub_contract?: string | null;
    lido_fee_address?: string | null;
    lido_fee_rate?: Decimal | null;
    owner?: string | null;
    stsei_reward_denom?: string | null;
    [k: string]: unknown;
  };
} | {
  dispatch_rewards: {
    [k: string]: unknown;
  };
};
export type Uint128 = string;
export type Decimal = string;
export interface InstantiateMsg {
  bsei_reward_contract: string;
  bsei_reward_denom: string;
  hub_contract: string;
  lido_fee_address: string;
  lido_fee_rate: Decimal;
  stsei_reward_denom: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  get_buffered_rewards: {
    [k: string]: unknown;
  };
} | {
  config: {
    [k: string]: unknown;
  };
};
export type RewardsDispatcherExecuteMsg = ExecuteMsg;