/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Addr = string;
export interface InstantiateMsg {
  duration: Uint128;
  gov?: Addr | null;
  kpt_fund: Addr;
  reward_controller_addr: Addr;
  rewards_token: Addr;
  staking_token: Addr;
  ve_kpt_boost: Addr;
}
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  update_staking_config: {
    gov?: Addr | null;
    kpt_fund?: Addr | null;
    reward_controller_addr?: Addr | null;
    rewards_token?: Addr | null;
    staking_token?: Addr | null;
    ve_kpt_boost?: Addr | null;
  };
} | {
  update_staking_state: {
    duration: Uint128;
  };
} | {
  get_reward: {};
} | {
  notify_reward_amount: {
    amount: Uint128;
  };
};
export type Binary = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export type QueryMsg = {
  reward_per_token: {};
} | {
  last_time_reward_applicable: {};
} | {
  get_boost: {
    account: Addr;
  };
} | {
  earned: {
    account: Addr;
  };
} | {
  query_staking_config: {};
} | {
  query_staking_state: {};
} | {
  get_user_updated_at: {
    account: Addr;
  };
} | {
  get_user_reward_per_token_paid: {
    account: Addr;
  };
};
export interface EarnedResponse {
  earned: Uint128;
}
export interface GetBoostResponse {
  boost: Uint128;
}
export interface GetUserRewardPerTokenPaidResponse {
  reward_per_token_paid: Uint128;
}
export interface GetUserUpdatedAtResponse {
  updated_at: Uint128;
}
export interface LastTimeRewardApplicableResponse {
  last_time_reward_applicable: Uint128;
}
export interface StakingConfigResponse {
  gov: Addr;
  kpt_fund: Addr;
  reward_controller_addr: Addr;
  rewards_token: Addr;
  staking_token: Addr;
  ve_kpt_boost: Addr;
}
export interface StakingStateResponse {
  duration: Uint128;
  finish_at: Uint128;
  reward_per_token_stored: Uint128;
  reward_rate: Uint128;
  total_supply: Uint128;
  updated_at: Uint128;
}
export interface RewardPerTokenResponse {
  reward_per_token: Uint128;
}
export type StakingRewardsExecuteMsg = ExecuteMsg;