/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  owner: Addr;
}
export type ExecuteMsg = {
  update_pair_config: {
    asset_infos: [AssetInfo, AssetInfo];
    max_spread?: Decimal | null;
    pair_address: Addr;
    to?: Addr | null;
  };
} | {
  change_owner: {
    new_owner: Addr;
  };
} | {
  update_pair_status: {
    asset_infos: [AssetInfo, AssetInfo];
    is_disabled: boolean;
  };
} | {
  update_pair_max_spread: {
    asset_infos: [AssetInfo, AssetInfo];
    max_spread: Decimal;
  };
} | {
  set_whitelist: {
    caller: Addr;
    is_whitelist: boolean;
  };
} | {
  swap_denom: {
    from_coin: Coin;
    target_denom: string;
  };
};
export type AssetInfo = {
  token: {
    contract_addr: Addr;
  };
} | {
  native_token: {
    denom: string;
  };
};
export type Decimal = string;
export type Uint128 = string;
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  query_config: {};
} | {
  query_is_swap_whitelist: {
    caller: Addr;
  };
} | {
  query_pair_config: {
    asset_infos: [AssetInfo, AssetInfo];
  };
} | {
  query_swap_info: {
    asset_infos: [AssetInfo, AssetInfo];
  };
};
export interface ConfigResponse {
  owner: Addr;
}
export type Boolean = boolean;
export interface PairConfigResponse {
  is_disabled: boolean;
  max_spread?: Decimal | null;
  pair_address: Addr;
  to?: Addr | null;
}
export interface SwapInfoResponse {
  total_amount_in: Uint128;
  total_amount_out: Uint128;
}
export type SwapExtentionExecuteMsg = ExecuteMsg;