/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./BlindBox.types";
import * as _1 from "./BlindBox.client";
import * as _2 from "./BlindBoxInviterReward.types";
import * as _3 from "./BlindBoxInviterReward.client";
import * as _4 from "./BlindBoxReward.types";
import * as _5 from "./BlindBoxReward.client";
export namespace blindBoxContracts {
  export const BlindBox = { ..._0,
    ..._1
  };
  export const BlindBoxInviterReward = { ..._2,
    ..._3
  };
  export const BlindBoxReward = { ..._4,
    ..._5
  };
}