/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  collateral_contract: string;
  control_contract: string;
  liquidation_contract: string;
  owner_addr: string;
  pool_contract: string;
  reward_book_contract: string;
}
export type ExecuteMsg = {
  update_config: {
    collateral_contract?: string | null;
    control_contract?: string | null;
    liquidation_contract?: string | null;
    pool_contract?: string | null;
    reward_book_contract?: string | null;
  };
} | {
  set_owner: {
    new_owner_addr: string;
  };
} | {
  accept_ownership: {};
} | {
  receive: Cw20ReceiveMsg;
} | {
  redeem_stable_coin: {
    redeem_amount: Uint128;
    redeemer: string;
  };
} | {
  withdraw_collateral: {
    collateral_amount: Uint128;
    collateral_contract: string;
    minter: string;
  };
} | {
  liquidate_collateral: {
    amount: Uint128;
    liquidator: string;
  };
} | {
  claim_rewards: {
    reward_contract: string;
  };
};
export type Uint128 = string;
export type Binary = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export type QueryMsg = {
  config: {};
} | {
  state: {};
};
export interface ConfigResponse {
  collateral_contract: string;
  control_contract: string;
  liquidation_contract: string;
  owner_addr: string;
  pool_contract: string;
  reward_book_contract: string;
}
export type Uint256 = string;
export interface StateResponse {
  total_amount: Uint256;
}
export type CustodyExecuteMsg = ExecuteMsg;