/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _52 from "./CentralControl.types";
import * as _53 from "./CentralControl.client";
import * as _54 from "./Custody.types";
import * as _55 from "./Custody.client";
import * as _56 from "./LiquidationQueue.types";
import * as _57 from "./LiquidationQueue.client";
import * as _58 from "./StablePool.types";
import * as _59 from "./StablePool.client";
export namespace cdpContracts {
  export const CentralControl = { ..._52,
    ..._53
  };
  export const Custody = { ..._54,
    ..._55
  };
  export const LiquidationQueue = { ..._56,
    ..._57
  };
  export const StablePool = { ..._58,
    ..._59
  };
}