/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _16 from "./CentralControl.types";
import * as _17 from "./CentralControl.client";
import * as _18 from "./Custody.types";
import * as _19 from "./Custody.client";
import * as _20 from "./LiquidationQueue.types";
import * as _21 from "./LiquidationQueue.client";
import * as _22 from "./StablePool.types";
import * as _23 from "./StablePool.client";
export namespace cdpContracts {
  export const CentralControl = { ..._16,
    ..._17
  };
  export const Custody = { ..._18,
    ..._19
  };
  export const LiquidationQueue = { ..._20,
    ..._21
  };
  export const StablePool = { ..._22,
    ..._23
  };
}