/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _34 from "./SwapExtention.types";
import * as _35 from "./SwapExtention.client";
export namespace contracts {
  export const SwapExtention = { ..._34,
    ..._35
  };
}