/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _30 from "./BassetConverter.types";
import * as _31 from "./BassetConverter.client";
import * as _32 from "./BassetToken.types";
import * as _33 from "./BassetToken.client";
export namespace convertContracts {
  export const BassetConverter = { ..._30,
    ..._31
  };
  export const BassetToken = { ..._32,
    ..._33
  };
}