/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.33.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Boost.types";
import * as _1 from "./Boost.client";
import * as _2 from "./Dispatcher.types";
import * as _3 from "./Dispatcher.client";
import * as _4 from "./Distribute.types";
import * as _5 from "./Distribute.client";
import * as _6 from "./Fund.types";
import * as _7 from "./Fund.client";
import * as _8 from "./Keeper.types";
import * as _9 from "./Keeper.client";
import * as _10 from "./Seilor.types";
import * as _11 from "./Seilor.client";
import * as _12 from "./Staking.types";
import * as _13 from "./Staking.client";
import * as _14 from "./Treasure.types";
import * as _15 from "./Treasure.client";
import * as _16 from "./VeSeilor.types";
import * as _17 from "./VeSeilor.client";
export namespace tokenContracts {
  export const Boost = { ..._0,
    ..._1
  };
  export const Dispatcher = { ..._2,
    ..._3
  };
  export const Distribute = { ..._4,
    ..._5
  };
  export const Fund = { ..._6,
    ..._7
  };
  export const Keeper = { ..._8,
    ..._9
  };
  export const Seilor = { ..._10,
    ..._11
  };
  export const Staking = { ..._12,
    ..._13
  };
  export const Treasure = { ..._14,
    ..._15
  };
  export const VeSeilor = { ..._16,
    ..._17
  };
}