/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _42 from "./Boost.types";
import * as _43 from "./Boost.client";
import * as _44 from "./Dispatcher.types";
import * as _45 from "./Dispatcher.client";
import * as _46 from "./Distribute.types";
import * as _47 from "./Distribute.client";
import * as _48 from "./Fund.types";
import * as _49 from "./Fund.client";
import * as _50 from "./Keeper.types";
import * as _51 from "./Keeper.client";
import * as _52 from "./Seilor.types";
import * as _53 from "./Seilor.client";
import * as _54 from "./Staking.types";
import * as _55 from "./Staking.client";
import * as _56 from "./Treasure.types";
import * as _57 from "./Treasure.client";
import * as _58 from "./VeSeilor.types";
import * as _59 from "./VeSeilor.client";
export namespace tokenContracts {
  export const Boost = { ..._42,
    ..._43
  };
  export const Dispatcher = { ..._44,
    ..._45
  };
  export const Distribute = { ..._46,
    ..._47
  };
  export const Fund = { ..._48,
    ..._49
  };
  export const Keeper = { ..._50,
    ..._51
  };
  export const Seilor = { ..._52,
    ..._53
  };
  export const Staking = { ..._54,
    ..._55
  };
  export const Treasure = { ..._56,
    ..._57
  };
  export const VeSeilor = { ..._58,
    ..._59
  };
}