/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Boost.types";
import * as _1 from "./Boost.client";
import * as _2 from "./Dispatcher.types";
import * as _3 from "./Dispatcher.client";
import * as _4 from "./Distribute.types";
import * as _5 from "./Distribute.client";
import * as _6 from "./DistributeCo.types";
import * as _7 from "./DistributeCo.client";
import * as _8 from "./Fund.types";
import * as _9 from "./Fund.client";
import * as _10 from "./Keeper.types";
import * as _11 from "./Keeper.client";
import * as _12 from "./Seilor.types";
import * as _13 from "./Seilor.client";
import * as _14 from "./Staking.types";
import * as _15 from "./Staking.client";
import * as _16 from "./StakingOnly.types";
import * as _17 from "./StakingOnly.client";
import * as _18 from "./Treasure.types";
import * as _19 from "./Treasure.client";
import * as _20 from "./VeSeilor.types";
import * as _21 from "./VeSeilor.client";
export namespace tokenContracts {
  export const Boost = { ..._0,
    ..._1
  };
  export const Dispatcher = { ..._2,
    ..._3
  };
  export const Distribute = { ..._4,
    ..._5
  };
  export const DistributeCo = { ..._6,
    ..._7
  };
  export const Fund = { ..._8,
    ..._9
  };
  export const Keeper = { ..._10,
    ..._11
  };
  export const Seilor = { ..._12,
    ..._13
  };
  export const Staking = { ..._14,
    ..._15
  };
  export const StakingOnly = { ..._16,
    ..._17
  };
  export const Treasure = { ..._18,
    ..._19
  };
  export const VeSeilor = { ..._20,
    ..._21
  };
}
