/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.33.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Addr, Uint128, InstantiateMsg, ExecuteMsg, Binary, Cw20ReceiveMsg, TreasureConfigMsg, QueryMsg, QueryUserInfosMsg, ConfigInfosResponse, TreasureConfig, TreasureState, UserInfosResponse, UserLockRecord, UserMintNftRecord, TreasureUserState, UserWithdrawRecord } from "./Treasure.types";
export interface TreasureReadOnlyInterface {
  contractAddress: string;
  queryConfigInfos: () => Promise<ConfigInfosResponse>;
  queryUserInfos: ({
    msg
  }: {
    msg: QueryUserInfosMsg;
  }) => Promise<UserInfosResponse>;
}
export class TreasureQueryClient implements TreasureReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.queryConfigInfos = this.queryConfigInfos.bind(this);
    this.queryUserInfos = this.queryUserInfos.bind(this);
  }

  queryConfigInfos = async (): Promise<ConfigInfosResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_config_infos: {}
    });
  };
  queryUserInfos = async ({
    msg
  }: {
    msg: QueryUserInfosMsg;
  }): Promise<UserInfosResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_user_infos: {
        msg
      }
    });
  };
}
export interface TreasureInterface {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateConfig: ({
    endTime,
    gov,
    integralRewardCoefficient,
    lockDuration,
    lockToken,
    mintNftCostIntegral,
    modNum,
    punishCoefficient,
    punishReceiver,
    startTime,
    winningNum
  }: {
    endTime?: number;
    gov?: Addr;
    integralRewardCoefficient?: Uint128;
    lockDuration?: number;
    lockToken?: Addr;
    mintNftCostIntegral?: Uint128;
    modNum?: number;
    punishCoefficient?: Uint128;
    punishReceiver?: Addr;
    startTime?: number;
    winningNum?: number[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  userWithdraw: ({
    amount
  }: {
    amount: Uint128;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  preMintNft: ({
    mintNum
  }: {
    mintNum: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class TreasureClient implements TreasureInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.userWithdraw = this.userWithdraw.bind(this);
    this.preMintNft = this.preMintNft.bind(this);
  }

  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee, memo, _funds);
  };
  updateConfig = async ({
    endTime,
    gov,
    integralRewardCoefficient,
    lockDuration,
    lockToken,
    mintNftCostIntegral,
    modNum,
    punishCoefficient,
    punishReceiver,
    startTime,
    winningNum
  }: {
    endTime?: number;
    gov?: Addr;
    integralRewardCoefficient?: Uint128;
    lockDuration?: number;
    lockToken?: Addr;
    mintNftCostIntegral?: Uint128;
    modNum?: number;
    punishCoefficient?: Uint128;
    punishReceiver?: Addr;
    startTime?: number;
    winningNum?: number[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        end_time: endTime,
        gov,
        integral_reward_coefficient: integralRewardCoefficient,
        lock_duration: lockDuration,
        lock_token: lockToken,
        mint_nft_cost_integral: mintNftCostIntegral,
        mod_num: modNum,
        punish_coefficient: punishCoefficient,
        punish_receiver: punishReceiver,
        start_time: startTime,
        winning_num: winningNum
      }
    }, fee, memo, _funds);
  };
  userWithdraw = async ({
    amount
  }: {
    amount: Uint128;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      user_withdraw: {
        amount
      }
    }, fee, memo, _funds);
  };
  preMintNft = async ({
    mintNum
  }: {
    mintNum: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pre_mint_nft: {
        mint_num: mintNum
      }
    }, fee, memo, _funds);
  };
}