/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint128 = string;
export interface InstantiateMsg {
  end_lock_time: number;
  gov?: Addr | null;
  lock_token: Addr;
  no_delay_punish_coefficient: Uint128;
  punish_receiver: Addr;
  start_lock_time: number;
  withdraw_delay_duration: number;
}
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  update_config: TreasureConfigMsg;
} | {
  user_withdraw: {
    amount: Uint128;
  };
} | {
  user_unlock: {
    amount: Uint128;
  };
} | {
  set_gov: {
    gov: Addr;
  };
} | {
  accept_gov: {};
};
export type Binary = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface TreasureConfigMsg {
  end_lock_time?: number | null;
  lock_token?: Addr | null;
  no_delay_punish_coefficient?: Uint128 | null;
  punish_receiver?: Addr | null;
  start_lock_time?: number | null;
  withdraw_delay_duration?: number | null;
}
export type QueryMsg = {
  query_config_infos: {};
} | {
  query_user_infos: {
    user: Addr;
  };
};
export interface ConfigInfosResponse {
  config: TreasureConfig;
  state: TreasureState;
}
export interface TreasureConfig {
  end_lock_time: number;
  gov: Addr;
  lock_token: Addr;
  new_gov?: Addr | null;
  no_delay_punish_coefficient: Uint128;
  punish_receiver: Addr;
  start_lock_time: number;
  withdraw_delay_duration: number;
  [k: string]: unknown;
}
export interface TreasureState {
  current_locked_amount: Uint128;
  current_unlock_amount: Uint128;
  total_locked_amount: Uint128;
  total_punish_amount: Uint128;
  total_withdraw_amount: Uint128;
  [k: string]: unknown;
}
export interface UserInfosResponse {
  user_state: TreasureUserState;
}
export interface TreasureUserState {
  current_locked_amount: Uint128;
  current_unlock_amount: Uint128;
  last_lock_time: number;
  last_unlock_time: number;
  total_locked_amount: Uint128;
  total_punish_amount: Uint128;
  total_unlock_amount: Uint128;
  total_withdraw_amount: Uint128;
  [k: string]: unknown;
}
export type TreasureExecuteMsg = ExecuteMsg;