/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.33.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Addr = string;
export interface InstantiateMsg {
  dust_reward_per_second: Uint128;
  end_lock_time: number;
  gov?: Addr | null;
  lock_token: Addr;
  mint_nft_cost_dust: Uint128;
  mod_num: number;
  nft_end_pre_mint_time: number;
  nft_start_pre_mint_time: number;
  no_delay_punish_coefficient: Uint128;
  punish_receiver: Addr;
  start_lock_time: number;
  winning_num: number[];
  withdraw_delay_duration: number;
}
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  update_config: TreasureConfigMsg;
} | {
  user_withdraw: {
    amount: Uint128;
  };
} | {
  user_unlock: {
    amount: Uint128;
  };
} | {
  pre_mint_nft: {
    mint_num: number;
  };
};
export type Binary = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface TreasureConfigMsg {
  dust_reward_per_second?: Uint128 | null;
  end_lock_time?: number | null;
  gov?: Addr | null;
  lock_token?: Addr | null;
  mint_nft_cost_dust?: Uint128 | null;
  mod_num?: number | null;
  nft_end_pre_mint_time?: number | null;
  nft_start_pre_mint_time?: number | null;
  no_delay_punish_coefficient?: Uint128 | null;
  punish_receiver?: Addr | null;
  start_lock_time?: number | null;
  winning_num?: number[] | null;
  withdraw_delay_duration?: number | null;
}
export type QueryMsg = {
  query_config_infos: {};
} | {
  query_user_infos: {
    user: Addr;
  };
};
export interface ConfigInfosResponse {
  config: TreasureConfig;
  state: TreasureState;
}
export interface TreasureConfig {
  dust_reward_per_second: Uint128;
  end_lock_time: number;
  gov: Addr;
  lock_token: Addr;
  mint_nft_cost_dust: Uint128;
  mod_num: number;
  nft_end_pre_mint_time: number;
  nft_start_pre_mint_time: number;
  no_delay_punish_coefficient: Uint128;
  punish_receiver: Addr;
  start_lock_time: number;
  winning_num: number[];
  withdraw_delay_duration: number;
  [k: string]: unknown;
}
export interface TreasureState {
  current_locked_amount: Uint128;
  current_unlock_amount: Uint128;
  total_cost_dust_amount: Uint128;
  total_locked_amount: Uint128;
  total_lose_nft_num: number;
  total_punish_amount: Uint128;
  total_unlock_amount: Uint128;
  total_win_nft_num: number;
  total_withdraw_amount: Uint128;
  [k: string]: unknown;
}
export interface UserInfosResponse {
  user_state: TreasureUserState;
}
export interface TreasureUserState {
  current_dust_amount: Uint128;
  current_locked_amount: Uint128;
  current_unlock_amount: Uint128;
  last_lock_time: number;
  last_unlock_time: number;
  lose_nft_num: number;
  total_cost_dust_amount: Uint128;
  total_locked_amount: Uint128;
  total_punish_amount: Uint128;
  total_unlock_amount: Uint128;
  total_withdraw_amount: Uint128;
  win_nft_num: number;
  [k: string]: unknown;
}
export type TreasureExecuteMsg = ExecuteMsg;