/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Addr, Uint128, InstantiateMsg, ExecuteMsg, Binary, Cw20ReceiveMsg, TreasureConfigMsg, QueryMsg, ConfigInfosResponse, TreasureConfig, TreasureState, UserInfosResponse, TreasureUserState } from "./Treasure.types";
export interface TreasureReadOnlyInterface {
  contractAddress: string;
  queryConfigInfos: () => Promise<ConfigInfosResponse>;
  queryUserInfos: ({
    user
  }: {
    user: Addr;
  }) => Promise<UserInfosResponse>;
}
export class TreasureQueryClient implements TreasureReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.queryConfigInfos = this.queryConfigInfos.bind(this);
    this.queryUserInfos = this.queryUserInfos.bind(this);
  }

  queryConfigInfos = async (): Promise<ConfigInfosResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_config_infos: {}
    });
  };
  queryUserInfos = async ({
    user
  }: {
    user: Addr;
  }): Promise<UserInfosResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_user_infos: {
        user
      }
    });
  };
}
export interface TreasureInterface {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateConfig: ({
    endLockTime,
    lockToken,
    noDelayPunishCoefficient,
    punishReceiver,
    startLockTime,
    withdrawDelayDuration
  }: {
    endLockTime?: number;
    lockToken?: Addr;
    noDelayPunishCoefficient?: Uint128;
    punishReceiver?: Addr;
    startLockTime?: number;
    withdrawDelayDuration?: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  userWithdraw: ({
    amount
  }: {
    amount: Uint128;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  userUnlock: ({
    amount
  }: {
    amount: Uint128;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setGov: ({
    gov
  }: {
    gov: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  acceptGov: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class TreasureClient implements TreasureInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.userWithdraw = this.userWithdraw.bind(this);
    this.userUnlock = this.userUnlock.bind(this);
    this.setGov = this.setGov.bind(this);
    this.acceptGov = this.acceptGov.bind(this);
  }

  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee, memo, _funds);
  };
  updateConfig = async ({
    endLockTime,
    lockToken,
    noDelayPunishCoefficient,
    punishReceiver,
    startLockTime,
    withdrawDelayDuration
  }: {
    endLockTime?: number;
    lockToken?: Addr;
    noDelayPunishCoefficient?: Uint128;
    punishReceiver?: Addr;
    startLockTime?: number;
    withdrawDelayDuration?: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        end_lock_time: endLockTime,
        lock_token: lockToken,
        no_delay_punish_coefficient: noDelayPunishCoefficient,
        punish_receiver: punishReceiver,
        start_lock_time: startLockTime,
        withdraw_delay_duration: withdrawDelayDuration
      }
    }, fee, memo, _funds);
  };
  userWithdraw = async ({
    amount
  }: {
    amount: Uint128;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      user_withdraw: {
        amount
      }
    }, fee, memo, _funds);
  };
  userUnlock = async ({
    amount
  }: {
    amount: Uint128;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      user_unlock: {
        amount
      }
    }, fee, memo, _funds);
  };
  setGov = async ({
    gov
  }: {
    gov: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_gov: {
        gov
      }
    }, fee, memo, _funds);
  };
  acceptGov = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      accept_gov: {}
    }, fee, memo, _funds);
  };
}